apiVersion: v1
kind: Secret
metadata:
  namespace: n8n
  name: postgres-secret
type: Opaque
stringData:
  POSTGRES_USER: kt-admin
  POSTGRES_PASSWORD: "blakeks1234!*"
  POSTGRES_DB: n8n
  POSTGRES_NON_ROOT_USER: kt-user
  POSTGRES_NON_ROOT_PASSWORD: "1234blakeks!*"